# 参考文献
 
***
- 1.[Julian Taylor, David Butler (2017). R Package ASMap: Efficient Genetic Linkage Map Construction and Diagnosis. Journal of Statistical Software, 79(6), 1-29.](https://www.jstatsoft.org/article/view/v079i06)

- 2.[R/qtl: A QTL mapping environment](https://rqtl.org/.)

- 3.[Li H, Durbin R: Fast and accurate short read alignment with Burrows-Wheeler transform. Bioinformatics 2009, 25(14):1754-1760.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2705234/)

- 4.[McKenna A, Hanna M, Banks E, et al. The Genome Analysis Toolkit: a MapReduce framework for analyzing next-generation DNA sequencing data[J]. Genome research, 2010, 20(9): 1297-1303.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2928508/)

- 5.[Cingolani P, Platts A, Wang L L, et al. (2012). A program for annotating and predicting the effects of single nucleotide polymorphisms, SnpEff: SNPs in the genome of Drosophila  melanogaster strain w1118; iso-2; iso-3[J]. Fly, 6(2): 80-92.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3679285/)

- 6.[Gonda, et al. Sequencing-based bin map construction of a tomato mapping population, facilitating high-resolution quantitative trait loci detection. Plant Genome. 2019.](https://pubmed.ncbi.nlm.nih.gov/30951101/)

- 7.[Gonda, I., Ashrafi, H., Lyon, D.A., Strickler, S.R., Hulse-Kemp, A.M., Ma, Q., Sun, H., Stoffel, K., Powell, A.F., Futrell, S., Thannhauser, T.W., Fei, Z., Van Deynze, A.E., Mueller, L.A., Giovannoni, J.J. and Foolad, M.R. (2019), Sequencing-Based Bin Map Construction of a Tomato Mapping Population, Facilitating High-Resolution Quantitative Trait Loci Detection. The Plant Genome, 12: 180010. ](https://acsess.onlinelibrary.wiley.com/doi/10.3835/plantgenome2018.02.0010)

- 8.[Lander E S, Botstein D. Mapping mendelian factors underlying quantitative traits using RFLP linkagemaps[J]. Genetics, 1989,121(1): 185-199.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1203601/)



# 附录

***

## 关联分析使用软件介绍

***


<p class='mark'>附表1 生信分析软件列表（待更新）</p>

```{r echo=FALSE}
library(knitr)
data <- read.delim('src/fujian.xls',sep='\t',header=T,check.names = F)
kable(data,table.attr = "html") %>%
kable_styling(bootstrap_options=c("striped","hover","condensed"))
```

## 相关软件下载链接如下：

- fastp：https://github.com/OpenGene/fastp

- BWA：http://bio-bwa.sourceforge.net/

- GATK：https://software.broadinstitute.org/gatk/

- SAMtools：http://www.htslib.org/

- Sentieon：https://www.sentieon.com/products/

- SnpEff：http://snpeff.sourceforge.net/

- ASMap：https://cran.r-project.org/web/packages/ASMap/index.html

- R/qtl：https://rqtl.org/download/

- Blast：https://blast.ncbi.nlm.nih.gov/Blast.cgi

## 附件说明及数据下载

***

### 文件解压缩方法

&emsp;&emsp;所有提供的文件均为 Linux 系统下的文件，压缩包使用“tar -zcvf ”命令压缩， 以下为不同 系统用户解压缩的方法：  Unix/Linux/Mac 用户:  使用 tar -zcvf *.tar.gz 命令 ；Windows 用户： 使用 WinRAR 软件解压缩。

### 文件打开或浏览方法

&emsp;&emsp;如果在本附录中无特殊说明，所有提供的文件均为 Linux 系统下文本文件，Unix/Linux 用 户可以使用 more 或 less 命令查看文本文件内容。对于 Windows 用户，一般文本文件可以使用 写字板或者 Excel 打开 。推荐使用开 Note Pad 打开超过 10M  以上的文本文件 ， 或选择 Unix/Linux/MacOS 系统在终端中打开相关文件。

&emsp;&emsp;数据中可能包含部分图像文件，一般图像文件后缀名为.png 、.pdf、.gif、tiff 等，对于图像文件，Windows 用户可以使用图片浏览器打开，Linux/Unix 用户使用 display 命令打开。

&emsp;&emsp;后缀名为 svg 的文件为文本格式描述的图像文件，Windows 用户需要安装 Adobe Illustrator 软件打开。Linux/Unix 用户可以使用 rsvg-view 命令查看。公司默认提供“pdf“格式的矢量图， 可利用"Adobe Illustrator"软件对该格式图片进行编辑。Linux 下的表格均为制表符（Tab）分割 的文本，为了便于阅读，建议使用 Excel 或 OpenOffice 等办公软件用表格形式打开，打开时请 用“Tab 分割”方式。


