---
title: |
  | **全基因组重测序混池关联分析**
  | **BSA结题报告**
date: "`r ifelse(params$docfmt == 'html','',format(Sys.time(), '%Y年%m月%d日'))`"
params:
  primer_design: no
  docfmt: html
  population: F2
  mutmap: no
  deepbsa: no
documentclass: article
classoption:
  - a4paper
  - titlepage
output:
  bookdown::html_document2:
    css:
      - static/css/bootstrap.min.css
      - static/css/styles.css
    df_print: paged
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    math_method: r-katex
    self_contained: true
    keep_md: true
    pandoc_args:
      - --standalone
      - --metadata=title:BSA结题报告
    fig_caption: true
    includes:
      in_header: static/html/header.html
      after_body: static/html/tailer.html
  bookdown::pdf_document2:
    toc: true
    toc_depth: 3
    includes:
      in_header: tex/header.tex
    keep_tex: true
    latex_engine: xelatex
    number_sections: true
---

```{r setup, include=FALSE}
here::i_am("report.rmd")
options(scipen=20)
library(tidyverse)
library(dplyr)
library(latex2exp)
library(kableExtra)
library(knitr)
library(DT)
library(slickR)
library(stringr)
htmlfmt <- (params$docfmt == "html")
pdffmt <- (params$docfmt != "html")
use_deepbsa <- (params$deepbsa != "no")
no_use_deepbsa <- (params$deepbsa == "no")
mutmap <- (params$mutmap != "no")
primer_design <- (params$primer_design == "yes")
no_primer_design <- (params$primer_design != "yes")
has_region <- (file.info("../file/all.region_stat.xls")$size != 0)
rna <- FALSE
root_dir <- here::here()
knitr::opts_knit$set(
  root.dir = root_dir
)
knitr::opts_chunk$set(
  fig.align = 'center',
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  out.width = if(htmlfmt) "100%" else "40%",
  fig.pos = "H",
  fig.ext = ".png"
)
dt_foot <- function(foot_vector){
  cat('<blockquote>\n<p>注：<p>\n<ul class="dt-footnotes">',
  paste0('<li class="dt-footnotes">',foot_vector,'</li>\n'),
  '</ul>','</blockquote>',sep="\n"
  )
}
kbl_foot <- function(input,label){
  footnote(
    kable_input=input,
    general = label,
    threeparttable = FALSE,
    general_title = "注："
  )
}
table_bline <- function(input){
  sub("\\\\endhead\n\n\\\\endfoot","\\\\endhead\n\\\\hline\n\\\\endfoot",input)
}
prettier <- function(number,small=0){
  prettyNum(big.mark = ",",nsmall=small,scientific=FALSE,round(number,digits = small))
}
tbl_prettier <- function(table,small=NA){
  out <- table
  csmall <- rep_len(small,ncol(out))
  for(i in seq_len(ncol(out))){
    if(!is.na(csmall[i]) && is.numeric(out[,i])){
      out[,i] <- prettier(out[,i],small=csmall[i])
    }
  }
  out
}
dt_caption <- function(title,label){
  cat('<table class="caption-only">', paste0("<caption>",
                      paste0("(#tab:",label,")"),
                      title,
                      "</caption>"),
                      "</table>", sep ="\n")
}
```

```{r, include=pdffmt}
knitr::asis_output('\\newpage\n\\setcounter{page}{1}\n')
```

```{r get-project-info-table}
project_info <- readLines('../file/project.info')
genome_info <- read.delim('../file/info.log', sep='\t', header=TRUE, check.names = FALSE, stringsAsFactors = FALSE)
project_info <- project_info[project_info!=""]
project_info <- unlist(strsplit(project_info[1],"\t"))
contract_number <- project_info[1]
project_number <- project_info[2]
client_name <- project_info[3]
genome_chinese <- genome_info[1,2]
genome_latin <- genome_info[2,2]
genome_name <- paste0(genome_chinese, "(", genome_latin, ")")
genome_size <- paste0(round(as.numeric(genome_info[4,2]), 2), "MB")
genome_scale <- genome_info[5,2]
genome_link <- genome_info[6,2]
if (length(project_info) < 7) {
    platform <- "Illumina NovaSeq X Plus"
    prepkit <- "Truseq Nano DNA HT Sample Prep Kit (Illumina USA)"
} else if (project_info[7] == "DNBSEQ-T7") {
    platform <- "DNBSeq T7"
    prepkit <- "MGIEasy Cell-free DNA Library Prep Kit"
} else {
    platform <- "Illumina NovaSeq X Plus"
    prepkit <- "Truseq Nano DNA HT Sample Prep Kit (Illumina USA)"
}
platform0 <- unlist(strsplit(platform, " "))[1]
project_info_table<- data.frame(
  info = c("合同编号","项目编号","物种信息","客户姓名","报告时间"),
  content=c(
    contract_number,
    project_number,
    genome_name,
    client_name,
    format(Sys.time(), "%F")
  )
)
names(project_info_table) <- c("项目信息","项目内容")
```

```{r echo=FALSE}
group_list_file <- read.delim('../file/group.list',sep='\t',header=F,check.names=F)
sample_number <- dim(group_list_file)[1]
p1_id <- group_list_file[group_list_file$V2=="P1",1]
p2_id <- group_list_file[group_list_file$V2=="P2",1]
mix1_id <- group_list_file[group_list_file$V2=="B1",1]
mix2_id <- group_list_file[group_list_file$V2=="B2",1]
```

```{r echo=FALSE}
raw_data_stat <- read.delim("../file/rawdata.xls", sep="\t", header=T,check.names=F)
arrange_raw_data_stat <- rbind(raw_data_stat[raw_data_stat$`Sample ID` == p1_id,],raw_data_stat[raw_data_stat$`Sample ID` == p2_id,],
        raw_data_stat[raw_data_stat$`Sample ID` == mix1_id,],raw_data_stat[raw_data_stat$`Sample ID` == mix2_id,])
```

```{r echo=FALSE}
clean_data_stat <- read.delim("../file/cleandata.xls", sep="\t", header=T,check.names=F)
arrange_clean_data_stat <- rbind(clean_data_stat[clean_data_stat$`Sample ID` == p1_id,],clean_data_stat[clean_data_stat$`Sample ID` == p2_id,],
                                 clean_data_stat[clean_data_stat$`Sample ID` == mix1_id,],clean_data_stat[clean_data_stat$`Sample ID` == mix2_id,])
p1_total_base <- paste0(round(clean_data_stat[clean_data_stat$`Sample ID` == p1_id,]$`Clean Bases（bp）`/1000000000,2), "G")
p2_total_base <- paste0(round(clean_data_stat[clean_data_stat$`Sample ID` == p2_id,]$`Clean Bases（bp）`/1000000000,2), "G")
mix1_total_base <- paste0(round(clean_data_stat[clean_data_stat$`Sample ID` == mix1_id,]$`Clean Bases（bp）`/1000000000,2), "G")
mix2_total_base <- paste0(round(clean_data_stat[clean_data_stat$`Sample ID` == mix2_id,]$`Clean Bases（bp）`/1000000000,2), "G")
p1_average_q30 <- paste0(clean_data_stat[clean_data_stat$`Sample ID` == p1_id,]$`Clean Q30（%）`, "%")
p2_average_q30 <- paste0(clean_data_stat[clean_data_stat$`Sample ID` == p2_id,]$`Clean Q30（%）`, "%")
mix1_average_q30 <- paste0(clean_data_stat[clean_data_stat$`Sample ID` == mix1_id,]$`Clean Q30（%）`, "%")
mix2_average_q30 <- paste0(clean_data_stat[clean_data_stat$`Sample ID` == mix2_id,]$`Clean Q30（%）`, "%")
```

```{r echo=FALSE}
align_stat <- read.delim("../file/align_stat.xls", sep="\t", header=T,check.names=F)
arrange_align_stat <- rbind(align_stat[align_stat$`Sample ID` == p1_id,],align_stat[align_stat$`Sample ID` == p2_id,],
                            align_stat[align_stat$`Sample ID` == mix1_id,],align_stat[align_stat$`Sample ID` == mix2_id,])
p1_average_depth <- paste0(align_stat[align_stat$`Sample ID` == p1_id,]$`Real Depth`, "X")
p2_average_depth <- paste0(align_stat[align_stat$`Sample ID` == p2_id,]$`Real Depth`, "X")
mix1_average_depth <- paste0(align_stat[align_stat$`Sample ID` == mix1_id,]$`Real Depth`, "X")
mix2_average_depth <- paste0(align_stat[align_stat$`Sample ID` == mix2_id,]$`Real Depth`, "X")
p1_mapped_ratio <- paste0(align_stat[align_stat$`Sample ID` == p1_id,]$`Mapped Ratio(%)`, "%")
p2_mapped_ratio <- paste0(align_stat[align_stat$`Sample ID` == p2_id,]$`Mapped Ratio(%)`, "%")
mix1_mapped_ratio <- paste0(align_stat[align_stat$`Sample ID` == mix1_id,]$`Mapped Ratio(%)`, "%")
mix2_mapped_ratio <- paste0(align_stat[align_stat$`Sample ID` == mix2_id,]$`Mapped Ratio(%)`, "%")
p1_coverage <- paste0(align_stat[align_stat$`Sample ID` == p1_id,]$`Coverage(%) (>=1x)`, "%")
p2_coverage <- paste0(align_stat[align_stat$`Sample ID` == p2_id,]$`Coverage(%) (>=1x)`, "%")
mix1_coverage <- paste0(align_stat[align_stat$`Sample ID` == mix1_id,]$`Coverage(%) (>=1x)`, "%")
mix2_coverage <- paste0(align_stat[align_stat$`Sample ID` == mix2_id,]$`Coverage(%) (>=1x)`, "%")
```

```{r echo=FALSE}
snp_stat <- read.delim("../file/snp_stat.xls", sep="\t", header=T, check.names=F)
arrange_snp_stat <- rbind(snp_stat[snp_stat$`Sample ID` == p1_id,],snp_stat[snp_stat$`Sample ID` == p2_id,],
                            snp_stat[snp_stat$`Sample ID` == mix1_id,],snp_stat[snp_stat$`Sample ID` == mix2_id,])
p1_snp_number <- snp_stat[snp_stat$`Sample ID` == p1_id,]$`SNP Number`
p2_snp_number <- snp_stat[snp_stat$`Sample ID` == p2_id,]$`SNP Number`
mix1_snp_number <- snp_stat[snp_stat$`Sample ID` == mix1_id,]$`SNP Number`
mix2_snp_number <- snp_stat[snp_stat$`Sample ID` == mix2_id,]$`SNP Number`
```

```{r echo=FALSE}
snp_anno <- read.delim("../file/snp_anno.xls", sep="\t", header=T, check.names=F)
arrange_snp_anno <- rbind(snp_anno[snp_anno$sampleID == p1_id,],snp_anno[snp_anno$sampleID == p2_id,],
                            snp_anno[snp_anno$sampleID == mix1_id,],snp_anno[snp_anno$sampleID == mix2_id,])
arrange_snp_anno <- arrange_snp_anno %>%
        select(sampleID, start_lost, stop_lost, stop_gained, missense_variant, synonymous_variant, intergenic_region)
colnames(arrange_snp_anno) <- c("Sample ID", "Start Lost", "Stop Lost", "Stop Gained", "Missense Variant",
                                "Synonymous Variant", "Intragenic Region")
```

```{r echo=FALSE}
snp_impact <- read.delim('../file/snp_impact.xls',sep='\t',header=T,check.names = F)
arrange_snp_impact <- rbind(snp_impact[snp_impact$sampleID == p1_id,],snp_impact[snp_impact$sampleID == p2_id,],
                            snp_impact[snp_impact$sampleID == mix1_id,],snp_impact[snp_impact$sampleID == mix2_id,])
arrange_snp_impact <- arrange_snp_impact %>%
    select(sampleID, HIGH, MODERATE, LOW, MODIFIER)
colnames(arrange_snp_impact)[1] <- 'Sample ID'
p1_snp_high_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == p1_id,]$`HIGH`
p1_snp_moderate_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == p1_id,]$`MODERATE`
p2_snp_high_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == p2_id,]$`HIGH`
p2_snp_moderate_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == p2_id,]$`MODERATE`
mix1_snp_high_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == mix1_id,]$`HIGH`
mix1_snp_moderate_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == mix1_id,]$`MODERATE`
mix2_snp_high_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == mix2_id,]$`HIGH`
mix2_snp_moderate_number <- arrange_snp_impact[arrange_snp_impact$`Sample ID` == mix2_id,]$`MODERATE`
```

```{r echo=FALSE}
indel_stat <- read.delim("../file/indel_stat.xls", sep="\t", header=T, check.names=F)
arrange_indel_stat <- rbind(indel_stat[indel_stat$`Sample ID` == p1_id,],indel_stat[indel_stat$`Sample ID` == p2_id,],
                            indel_stat[indel_stat$`Sample ID` == mix1_id,],indel_stat[indel_stat$`Sample ID` == mix2_id,])
p1_indel_number <- indel_stat[indel_stat$`Sample ID` == p1_id,]$`Insert Number` + indel_stat[indel_stat$`Sample ID` == p1_id,]$`Delete Number`
p2_indel_number <- indel_stat[indel_stat$`Sample ID` == p2_id,]$`Insert Number` + indel_stat[indel_stat$`Sample ID` == p2_id,]$`Delete Number`
mix1_indel_number <- indel_stat[indel_stat$`Sample ID` == mix1_id,]$`Insert Number` + indel_stat[indel_stat$`Sample ID` == mix1_id,]$`Delete Number`
mix2_indel_number <- indel_stat[indel_stat$`Sample ID` == mix2_id,]$`Insert Number` + indel_stat[indel_stat$`Sample ID` == mix2_id,]$`Delete Number`
```

```{r echo=FALSE}
indel_anno <- read.delim("../file/indel_anno.xls", sep="\t", header=T, check.names=F)
arrange_indel_anno <- rbind(indel_anno[indel_anno$sampleID == p1_id,],indel_anno[indel_anno$sampleID == p2_id,],
                            indel_anno[indel_anno$sampleID == mix1_id,],indel_anno[indel_anno$sampleID == mix2_id,])
arrange_indel_anno <- arrange_indel_anno %>%
        select(sampleID, frameshift_variant, intergenic_region, intragenic_variant, start_lost, stop_gained, stop_lost)
colnames(arrange_indel_anno) <- c("Sample ID","Frameshift Variant", "Intergenic Region", "Intragenic Variant",
                                "Start Lost", "Stop Gained", "Stop Lost")
```

```{r echo=FALSE}
indel_impact <- read.delim('../file/indel_impact.xls',sep='\t',header=T,check.names = F)
arrange_indel_impact <- rbind(indel_impact[indel_impact$sampleID == p1_id,],indel_impact[indel_impact$sampleID == p2_id,],
                                indel_impact[indel_impact$sampleID == mix1_id,],indel_impact[indel_impact$sampleID == mix2_id,])
arrange_indel_impact <- arrange_indel_impact %>%
    select(sampleID, HIGH, MODERATE, LOW, MODIFIER)
colnames(arrange_indel_impact)[1] <- 'Sample ID'
p1_indel_high_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == p1_id,]$`HIGH`
p1_indel_moderate_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == p1_id,]$`MODERATE`
p2_indel_high_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == p2_id,]$`HIGH`
p2_indel_moderate_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == p2_id,]$`MODERATE`
mix1_indel_high_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == mix1_id,]$`HIGH`
mix1_indel_moderate_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == mix1_id,]$`MODERATE`
mix2_indel_high_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == mix2_id,]$`HIGH`
mix2_indel_moderate_number <- arrange_indel_impact[arrange_indel_impact$`Sample ID` == mix2_id,]$`MODERATE`
```

```{r stat-all-region, echo=FALSE}
if (has_region){
  all_region_stat <- read.delim("../file/all.region_stat.xls", sep="\t", header=T, check.names=F)
  separate_result <- all_region_stat %>%
          separate(Region, into=c("Chrom", "Start_pos", "End_pos"), sep=":")
  index_df <- separate_result[separate_result$Method == "index-slid",]
  loess_df <- separate_result[separate_result$Method == "index-loess",]
  gprime_df <- separate_result[separate_result$Method == "Gprime",]
  ed_df <- separate_result[separate_result$Method == "Euclidean",]
  deepbsa_dl_df <- separate_result[separate_result$Method == "DeepBSA_DL",]
  deepbsa_k_df <- separate_result[separate_result$Method == "DeepBSA_K",]
  index_num <- dim(index_df)[1]
  loess_num <- dim(loess_df)[1]
  gprime_num <- dim(gprime_df)[1]
  ed_num <- dim(ed_df)[1]
  deepbsa_dl_num <- dim(deepbsa_dl_df)[1]
  deepbsa_k_num <- dim(deepbsa_k_df)[1]
  index_length <- paste0(round(sum(as.numeric(index_df$End_pos) - as.numeric(index_df$Start_pos))/1000000,2), "MB")
  loess_length <- paste0(round(sum(as.numeric(loess_df$End_pos) - as.numeric(loess_df$Start_pos))/1000000,2), "MB")
  gprime_length <- paste0(round(sum(as.numeric(gprime_df$End_pos) - as.numeric(gprime_df$Start_pos))/1000000,2), "MB")
  ed_length <- paste0(round(sum(as.numeric(ed_df$End_pos) - as.numeric(ed_df$Start_pos))/1000000,2), "MB")
  deepbsa_dl_length <- paste0(round(sum(as.numeric(deepbsa_dl_df$End_pos) - as.numeric(deepbsa_dl_df$Start_pos))/1000000,2), "MB")
  deepbsa_k_length <- paste0(round(sum(as.numeric(deepbsa_k_df$End_pos) - as.numeric(deepbsa_k_df$Start_pos))/1000000,2), "MB")
}else{
  index_num = 0
  loess_num = 0
  gprime_num = 0
  ed_num = 0
  deepbsa_dl_num = 0
  deepbsa_k_num = 0
  index_length = 0
  loess_length = 0
  gprime_length = 0
  ed_length = 0
  deepbsa_dl_length = 0
  deepbsa_k_length = 0
}
if(index_num!=0){
  error_message <- try(read.delim("../file/index.degfile.xls", sep="\t", header=F, check.names=F), silent = TRUE)
  if (class(error_message) == "try-error"){
    index_transcript <- 0
    index_gene <- 0
  }else{
    index_gene <- read.delim("../file/index.degfile.xls", sep="\t", header=F, check.names=F)
    index_transcript <- read.delim("../file/index.transcript.degfile.xls", sep="\t", header=F, check.names=F)
    index_gene <- dim(unique(index_gene))[1]
    index_transcript <- dim(index_transcript)[1]
  }
}else{
  index_transcript <- 0
  index_gene <- 0
}
if(loess_num!=0){
  error_message <- try(read.delim("../file/loess.degfile.xls", sep="\t", header=F, check.names=F), silent = TRUE)
  if (class(error_message) == "try-error"){
    loess_transcript <- 0
    loess_gene <- 0
  }else{
    loess_gene <- read.delim("../file/loess.degfile.xls", sep="\t", header=F, check.names=F)
    loess_transcript <- read.delim("../file/loess.transcript.degfile.xls", sep="\t", header=F, check.names=F)
    loess_gene <- dim(unique(loess_gene))[1]
    loess_transcript <- dim(loess_transcript)[1]
  }
}else{
  loess_transcript <- 0
  loess_gene <- 0
}
if(gprime_num!=0){
  error_message <- try(read.delim("../file/Gprime.degfile.xls", sep="\t", header=F, check.names=F), silent = TRUE)
  if (class(error_message) == "try-error"){
    gprime_transcript <- 0
    gprime_gene <- 0
  }else{
    gprime_gene <- read.delim("../file/Gprime.degfile.xls", sep="\t", header=F, check.names=F)
    gprime_transcript <- read.delim("../file/Gprime.transcript.degfile.xls", sep="\t", header=F, check.names=F)
    gprime_gene <- dim(unique(gprime_gene))[1]
    gprime_transcript <- dim(gprime_transcript)[1]
  }
}else{
  gprime_transcript <- 0
  gprime_gene <- 0
}
if(ed_num!=0){
  error_message <- try(read.delim("../file/ED.degfile.xls", sep="\t", header=F, check.names=F), silent = TRUE)
  if (class(error_message) == "try-error"){
    ed_transcript <- 0
    ed_gene <- 0
  }else{
    ed_gene <- read.delim("../file/ED.degfile.xls", sep="\t", header=F, check.names=F)
    ed_transcript <- read.delim("../file/ED.transcript.degfile.xls", sep="\t", header=F, check.names=F)
    ed_gene <- dim(unique(ed_gene))[1]
    ed_transcript <- dim(ed_transcript)[1]
  }
}else{
  ed_transcript <- 0
  ed_gene <- 0
}
if(deepbsa_dl_num!=0){
  deepbsa_dl_gene <- read.delim("../file/DeepBSA_DL.degfile.xls", sep="\t", header=F, check.names=F)
  deepbsa_dl_transcript <- read.delim("../file/DeepBSA_DL.transcript.degfile.xls", sep="\t", header=F, check.names=F)
  deepbsa_dl_gene <- dim(unique(deepbsa_dl_gene))[1]
  deepbsa_dl_transcript <- dim(deepbsa_dl_transcript)[1]
}else{
  deepbsa_dl_transcript <- 0
  deepbsa_dl_gene <- 0
}
if(deepbsa_k_num!=0){
  deepbsa_k_gene <- read.delim("../file/DeepBSA_K.degfile.xls", sep="\t", header=F, check.names=F)
  deepbsa_k_transcript <- read.delim("../file/DeepBSA_K.transcript.degfile.xls", sep="\t", header=F, check.names=F)
  deepbsa_k_gene <- dim(unique(deepbsa_k_gene))[1]
  deepbsa_k_transcript <- dim(deepbsa_k_transcript)[1]
}else{
  deepbsa_k_transcript <- 0
  deepbsa_k_gene <- 0
}
```

```{r params-info, echo=FALSE}
poptype <- ifelse(params$population == "F1", "杂交群体", "近交群体")
params_info <- read.delim("../file/params.xls", sep=":", header=F, check.names=F, colClasses="character")
index_winsize <- params_info[params_info$V1=="index_winsize",2]
index_winsize_handle <- as.character(as.numeric(index_winsize)/1000000)
index_stepsize <- params_info[params_info$V1=="index_stepsize",2]
index_stepsize_handle <- as.character(as.numeric(index_stepsize)/1000)
index_bootstrap <- params_info[params_info$V1=="index_bootstrap",2]
index_p <- params_info[params_info$V1=="index_p",2]
loess_q <- params_info[params_info$V1=="loess_q",2]
loess_q_handle <- as.numeric(loess_q)*100
gprime_winsize <- params_info[params_info$V1=="gprime_winsize",2]
gprime_winsize_handle <- as.character(as.numeric(gprime_winsize)/1000000)
gprime_q <- params_info[params_info$V1=="gprime_q",2]
ed_winsize <- params_info[params_info$V1=="ed_winsize",2]
ed_winsize_handle <- as.character(as.numeric(ed_winsize)/1000000)
ed_stepsize <- params_info[params_info$V1=="ed_stepsize",2]
ed_stepsize_handle <- as.character(as.numeric(ed_stepsize)/1000000)
ed_q <- params_info[params_info$V1=="ed_q",2]
ed_q_handle <- as.numeric(ed_q)*100
index_minmarker <- as.numeric(params_info[params_info$V1=="index_minmarker",2])
index_minmarker <- ifelse(length(index_minmarker)>0, index_minmarker, 10)
loess_minmarker <- as.numeric(params_info[params_info$V1=="loess_minmarker",2])
loess_minmarker <- ifelse(length(loess_minmarker)>0, loess_minmarker, 10)
ed_minmarker <- as.numeric(params_info[params_info$V1=="ed_minmarker",2])
ed_minmarker <- ifelse(length(ed_minmarker)>0, ed_minmarker, 10)
gprime_minmarker <- as.numeric(params_info[params_info$V1=="gprime_minmarker",2])
gprime_minmarker <- ifelse(length(gprime_minmarker)>0, gprime_minmarker, 10)
```


```{r project-info-table, eval=htmlfmt}
kable(project_info_table, "html") %>%
        kable_styling(bootstrap_options=c("striped","hover","condensed"))
```

```{r first-page, eval=pdffmt}
knitr::asis_output(sprintf(paste(readLines("tex/first_page.tex"),collapse="\n"),contract_number,genome_chinese,sample_number))
```


```{r workflow-base, results='asis'}
cat(
  knitr::knit_child('rmd/01.workflow_common.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r workflow-table, results='asis'}
cat(
  knitr::knit_child('rmd/01.workflow_table.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r workflow-module-use-deepbsa, results='asis', eval=use_deepbsa}
cat(
  knitr::knit_child('rmd/01.workflow_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r workflow-module-no-use-deepbsa, results='asis', eval=no_use_deepbsa}
cat(
  knitr::knit_child('rmd/01.workflow_no_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r workflow-pipeline, results='asis'}
cat(
  knitr::knit_child('rmd/01.workflow_pipeline_common.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r fastq-qc-module, results='asis'}
cat(
  knitr::knit_child('rmd/02.Fastq_qc.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r mapping-module, results='asis'}
cat(
  knitr::knit_child('rmd/03.Align.rmd', envir = globalenv(), quiet = TRUE)
  )
```


```{r snp-module, results='asis'}
cat(
  knitr::knit_child('rmd/04.SNP.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r indel-module, results='asis'}
cat(
  knitr::knit_child('rmd/05.Indel.rmd', envir = globalenv(), quiet = TRUE)
  )
```

## BSA关联分析

```{r marker-filter-module, results='asis'}
cat(
  knitr::knit_child('rmd/06.marker_filter.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r index-module, results='asis' }
cat(
  knitr::knit_child('rmd/07.index.rmd', envir = globalenv(), quiet = TRUE)
  )
```


```{r gprime-module, results='asis', eval = file.exists("../file/Gprime.png")}
cat(
  knitr::knit_child('rmd/08.gprime.rmd', envir = globalenv(), quiet = TRUE)
  )
```


```{r ed-module, results='asis', eval = file.exists("../file/ED.png")}
cat(
  knitr::knit_child( 'rmd/09.ed.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r deepbsa-module, results='asis', eval=use_deepbsa}
cat(
  knitr::knit_child( 'rmd/13.deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
```


```{r region-module_use_deepbsa, results='asis', eval=use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/10.candidate_region_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r deepbsa-module_no_use_deepbsa, results='asis', eval=no_use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/10.candidate_region_no_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r go-enrich-module_use_deepbsa, results='asis', eval=use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/11.GO_enrich_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r go-enrich-module_no_use_deepbsa, results='asis', eval=no_use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/11.GO_enrich_no_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r kegg-enrich-module_use_deepbsa, results='asis', eval=use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/12.KEGG_enrich_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r kegg-enrich-module_no_use_deepbsa, results='asis', eval=no_use_deepbsa}
if(has_region){
cat(
  knitr::knit_child( 'rmd/12.KEGG_enrich_no_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
```

```{r primer-design-module_use_deepbsa, results='asis', eval=use_deepbsa}
if(has_region){
if (primer_design){
cat(
  knitr::knit_child( 'rmd/14.primer_design_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
}
```

```{r primer-design-module_no_use_deepbsa, results='asis', eval=no_use_deepbsa}
if(has_region){
if (primer_design){
cat(
  knitr::knit_child( 'rmd/14.primer_design_no_use_deepbsa.rmd', envir = globalenv(), quiet = TRUE)
  )
}
}
```


```{r, include=pdffmt}
knitr::asis_output('\\newpage\n')
```

```{r appendix-module, results='asis'}
cat(
  knitr::knit_child('rmd/99.appendix_common.rmd', envir = globalenv(), quiet = TRUE)
  )
```

```{r, include=pdffmt}
knitr::asis_output('\\newpage\n\n\\newpage\n')
```