# 参考文献

- 1. [Cingolani P, Adrian P, Le L W, et al. 2012. “A Program for Annotating and Predicting the Effects of Single Nucleotide Polymorphisms, SnpEff.” Fly 6 (2): 80–92.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC52814/)
- 2. [Hill J T, Bradley L D, Brent W B, et al. 2013. “MMAPPR: Mutation Mapping Analysis Pipeline for Pooled RNA-Seq.” Genome Research 23 (4): 687–97.](https://pubmed.ncbi.nlm.nih.gov/23289725/)
- 3. [Jung Y, Dongsu H. 2022. “BWA-MEME: BWA-MEM Emulated with a Machine Learning Approach.” Bioinformatics 38 (9): 2404–13.](https://pubmed.ncbi.nlm.nih.gov/28027425/)
- 5. [Magwene P M, John H W, John K K. 2011. “The Statistics of Bulk Segregant Analysis Using Next Generation Sequencing.” PLOS Computational Biology 7 (11): e1002255.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2705234/)
- 6. [McKenna A, Matthew H, Eric B, et al. 2010. “The Genome Analysis Toolkit: A MapReduce Framework for Analyzing next-Generation DNA Sequencing Data.” Genome Research 20 (9): 1297–1303.](https://genome.cshlp.org/content/20/9/1297.long)
- 7. [Michelmore R W, Paran I, Kesseli R V. 1991. “Identification of Markers Linked to Disease-Resistance Genes by Bulked Segregant Analysis: A Rapid Method to Detect Markers in Specific Genomic Regions by Using Segregating Populations.” Proceedings of the National Academy of Sciences of the United States of America 88 (21): 9828–32.](https://pubmed.ncbi.nlm.nih.gov/22728672/)
- 8. [Takagi H, Akira A, Kentaro Y, et al. 2013. “QTL-Seq: Rapid Mapping of Quantitative Trait Loci in Rice by Whole Genome Resequencing of DNA from Two Bulked Populations.” The Plant Journal: For Cell and Molecular Biology 74 (1): 174–83. ](https://pubmed.ncbi.nlm.nih.gov/22072954/)
- 9. [Yu G, Wang LG, et al. 2012. ”clusterProfiler: an R package for comparing biological themes among gene clusters.“ OMICS.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3339379/)

# 附录

***

## 软件列表

***


<p class='mark'> BSA 分析软件介绍</p>

```{r echo=FALSE}
library(knitr)
data <- read.delim('src/software.xls',sep='\t',header=T,check.names = F)
kable(data,table.attr = "html") %>%
kable_styling(bootstrap_options=c("striped","hover","condensed"))
```

## 相关软件下载链接如下：

***

- fastp 0.23.2：https://github.com/OpenGene/fastp

- BWA-MEME 1.0.5：https://github.com/kaist-ina/BWA-MEME

- SAMtools 1.15.1：http://www.htslib.org/

- Sentieon 202112.06：https://www.sentieon.com/products/

- SnpEff 5.1d：http://snpeff.sourceforge.net/

- R 4.2.2: https://cloud.r-project.org/

- R/clusterProfiler: http://master.bioconductor.org/packages/release/bioc/html/clusterProfiler.html

## 附件说明及数据下载

***

### 文件解压缩方法

&emsp;&emsp;所有提供的文件均为 Linux 系统下的文件，压缩包使用 “tar -zcvf” 命令压缩， 以下为不同系统用户解压缩的方法：Unix/Linux/Mac 用户:  使用 tar -zcvf *.tar.gz 命令；Windows 用户：使用 WinRAR 软件解压缩

### 文件打开或浏览方法

&emsp;&emsp;如果在本附录中无特殊说明，所有提供的文件均为 Linux 系统下文本文件，Unix/Linux 用 户可以使用 more 或 less 命令查看文本文件内容。对于 Windows 用户，一般文本文件可以使用写字板或者 Excel 打开 。推荐使用开 Note Pad 打开超过 10M  以上的文本文件，或选择 Unix/Linux/MacOS 系统在终端中打开相关文件。

&emsp;&emsp;数据中可能包含部分图像文件，一般图像文件后缀名为.png 、.pdf、.gif、tiff 等，对于图像文件，Windows 用户可以使用图片浏览器打开，Linux/Unix 用户使用 display 命令打开。

&emsp;&emsp;后缀名为 svg 的文件为文本格式描述的图像文件，Windows 用户需要安装 Adobe Illustrator 软件打开。Linux/Unix 用户可以使用 rsvg-view 命令查看。公司默认提供“pdf“格式的矢量图，可利用 "Adobe Illustrator" 软件对该格式图片进行编辑。Linux 下的表格均为制表符（Tab）分割 的文本，为了便于阅读，建议使用 Excel 或 OpenOffice 等办公软件用表格形式打开，打开时请 用 “Tab” 分割方式。
