01.fastq_qc	folder_1	质控结果文件夹
qc.stat.txt	file	质控统计表
结果说明文档.txt	file	结果说明文档
json	folder_2	fastp结果
control.qual.pdf	file	control样本碱基错误率分布例图(pdf版本)
control.qual.png	file	control样本碱基错误率分布例图(png版本)
control.base.pdf	file	control样本碱基组成分布例图(pdf版本)
control.base.png	file	control样本碱基组成分布例图(png版本)
control.json	file	control样本质控结果
case.qual.pdf	file	case样本碱基错误率分布例图(pdf版本)
case.qual.png	file	case样本碱基错误率分布例图(png版本)
case.base.pdf	file	case样本碱基组成分布例图(pdf版本)
case.base.png	file	case样本碱基组成分布例图(png版本)
case.json	file	case样本质控结果
02.reference	folder_1	参考基因组信息文件夹
readme.txt	file	文件详细介绍说明
ref.fa	file	参考基因组文件
ref.gtf	file	参考基因组注释文件
ref.cds.fa	file	参考基因组（编码区）文件
ref.protein.fa	file	参考基因组（蛋白）文件
ref.genome.summary.xls	file	参考基因组序列统计表
03.mappingStat	folder_1	比对结果文件夹
readme.txt	file	文件详细介绍说明
all.summary.stats	file	样品比对统计结果汇总表
control.depth.pdf	file	control基因组比对测序深度图(pdf版本)
control.depth.png	file	control基因组比对测序深度图(png版本)
control.coverage.pdf	file	control基因组比对覆盖度图(pdf版本)
control.coverage.png	file	control基因组比对覆盖度图(png版本)
control.insert.pdf	file	control基因组比对插入片段长度图(pdf版本)
control.insert.png	file	control基因组比对插入片段长度图(png版本)
case.depth.pdf	file	case基因组比对测序深度图(pdf版本)
case.depth.png	file	case基因组比对测序深度图(png版本)
case.coverage.pdf	file	case基因组比对覆盖度图(pdf版本)
case.coverage.png	file	case基因组比对覆盖度图(png版本)
case.insert.pdf	file	case基因组比对插入片段长度图(pdf版本)
case.insert.png	file	case基因组比对插入片段长度图(png版本)
04.crispr_off_target	folder_1	脱靶率结果文件夹
homo_region.result.xls	file	同源区域结果文件
homo_region.stat.xls	file	同源区域结果统计
target_info.xls	file	靶点和脱靶位点结果
target_stat	file	靶点和脱靶位点统计表
homo_region_seqlogo.pdf	file	同源区域seqlogo图(pdf版)
homo_region_seqlogo.png	file	同源区域seqlogo图(png版)
